### ISSUE TITLE
put on `s3` misses version params

### ISSUE THREAD

**Issue by EugenMayer** [spring-projects/atom-concourse#3]
under the s3 resource the paramter `version` is fairly important:

```yml
put:
   params:
     file:                    myresorce/myartifact*.jr
     version:             mysemver-ver/number
```

its missing in the concourse plugin
